### ISSUE TITLE
How to obtain --imagenet_ train_ path

### ISSUE THREAD

**Issue by Leonardo0325** [nelson1425/EfficientAD#1]
Hello，Thanks for your work.How can I obtain --imagenet_ train_ path？

**Comment by nelson1425** [comment]
Training requires ImageNet stored somewhere. Download ImageNet training images from https://www.kaggle.com/competitions/imagenet-object-localization-challenge/data or set `--imagenet_train_path` of `efficientad.py` to other folder with general images in children folders.
