### ISSUE TITLE
Can the pre-trained model of the teacher network 'teacher_small.pth' be trained by myself？

### ISSUE THREAD

**Issue by William9Baker** [nelson1425/EfficientAD#15]

**Comment by Ehteshamciitwah** [comment]
I think the teacher_small.pth is given by the author. We need to use efficientAd file to train student and autoencoder.

**Comment by William9Baker** [comment]
> 

Ok, thanks.

**Comment by William9Baker** [comment]
> I think the teacher_small.pth is given by the author. We need to use efficientAd file to train student and autoencoder.

I found it in 'pretraining.py'. It can train the model of 'teacher_small.pth'.

**Comment by yujins02** [comment]
How were you to evaluate following pre-training?


> > I think the teacher_small.pth is given by the author. We need to use efficientAd file to train student and autoencoder.
> 
> I found it in 'pretraining.py'. It can train the model of 'teacher_small.pth'.

How were you to evaluate following pre-training?
