### ISSUE TITLE
The image_size

### ISSUE THREAD

**Issue by Sencc** [nelson1425/EfficientAD#24]
Hello, Thank you for your work.
During training, does the image_size of the data need to be 256?

**Comment by Sencc** [comment]
When I change the image_size to 512,it got the error:
`RuntimeError: The size of tensor a (56) must match the size of tensor b (120) at non-singleton dimension 3`

**Comment by Sencc** [comment]
Need to change the upsampling of the decoder

**Comment by gzhxxx** [comment]
> Need to change the upsampling of the decoder

hi! could you please share the solution to train images with other sizes? thank you very much

**Comment by Sencc** [comment]
> > Need to change the upsampling of the decoder
> 
> hi! could you please share the solution to train images with other sizes? thank you very much

Hi,I only tried 512, and other dimensions are corrected and revised.

**Comment by ZHIZIHUABU** [comment]
@Sencc  请问是修改common.py和benchmark.py中的decoder部分两个'56'吗

**Comment by Sencc** [comment]
> @Sencc 请问是修改common.py和benchmark.py中的decoder部分两个'56'吗

You need to modify Upsample in get_autoencoder() of common.py.

**Comment by watertianyi** [comment]
@Sencc 
Currently, image sizes smaller than 256 are not supported. My image is only 64X64. What should I do?
