### ISSUE TITLE
mvtec_ad_evaluation.tar.xz

### ISSUE THREAD

**Issue by Jypeng-64** [nelson1425/EfficientAD#3]
mvtec_ad_evaluation.tar.xz
 If I can't connect to this link, is there any other way to get this file

**Comment by Jypeng-64** [comment]
I have solved the problem.Thanks again for your contribution!

**Comment by yufanfanwu-beep** [comment]
> I have solved the problem.Thanks again for your contribution!

I also encountered the same problem. Could you please tell me how you solved it?
